#IfWinActive,Notepad++
:*:c#+::LALALA
:*:f#::for ()`r{`r}
#IfWinActive,
:*C:aucjh::auch
:*:auhc::auch
:*C1:besogrt::besorgt
:*:bruacht::braucht
:*:dafpr::dafür
::dafur::dafür
:*:danek::danke
::dei::die
::didnt::didn't
:*:doer::oder
:*:doesnt::doesn't
::dont::don't
:*:dont'::don't
:*:ecth::echt
:*:eig.::eigentlich
::eric@::eric@goodsoul.de
:*C:eRiOC::ëRiC
:*C:eRo::eRi
:*:Erw.::Erweiterung
:*:esle::else
:*C:FF.::Firefox
:*:fidn::find
:*:flaot::float
:*:fm..::from maya import cmds
:*:for#::for (^v{Backspace} in ^v)`r{{}`r`r{}}{Up}{End}{Tab} ; don't escape modifiers
:*:fpr::für
:*:fuer::für
:*C:Geb.::Geburtstag
:*:gescuht::gesucht
:*:geshene::gesehen
:*:ggf.::gegebenenfalls
:*C:Groese::Größe
::Gruse::Grüße
:*:insg.::insgesamt
:*:interes.::interessant
:*:ir.::irgend
:*:irg.::irgendwie
:*:irn.::irgendwann
:*:iro.::irgendwo
:*:irs.::irgendwas
::its::it's
:*:ivh::ich
:*:jmd.::jemand
:*:jsut::just
:*:ka.::keine Ahnung
:*:keien::keine
::koennen::können
:*:kp.::kein Problem
:*:machne::machen
:*:masig::mäßig
:*:meien::meine
:*:mom.::Moment
:*:mri::mir
:*C:mti::mit
::mw.::mittlerweile
:*:nat.::natürlich
:*:ncih::nich
:*:nciht::nicht
:*:ncith::nicht
:*:nicth::nicht
:*:nioch::noch
:*:np.::no problem
:*:okko::okok
:*:pardin::pardon
:*:passiet::passiert
:*:prob.::Problem
:*:rechenr::rechner
:C:Rene::René
:*:repro.::reproduzieren
:*:sefl::self
:*:sel.f::self.
:*:shcon::schon
:*:shcön::schön
::sher::sehr
:*:shwo::show
:*:sien::sein
:*:spami::Spamihilator
:*:stekcne::stecken
:*:strnig::string
::Suse::Süße
:*:taht::that
::thats::that's
:*:ua.::unter anderem
:*:uach::auch
:*:uberhaupt::überhaupt
:*:ubr.::übrigens
:*:uch::ich
:*:udn::und
:*C1:UHK::UserHotkeys
:*:ung.::ungefähr
:*:versch.::verschiedene
:*:viell.::vielleicht
:*:voila::voilà
:*:waht::what
:*:we.::Wochenende
:*:weider::wieder
:*:Weih.::Weihnachten
:*:weiso::wieso
:*:welceh::welche
::whats::what's
:*:wiech::weich
:*:wiedr::wieder
:*:woceh::woche
:*:ws.::wahrscheinlich
:*C:xXx::
msgbox Hali!
msgbox Hallo!
Return
#IfWinActive,
